run:
  timeout: 10m
  tests: false

severity:
  default-severity: warning
  case-sensitive: false

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "ST1000: at least one file in a package should have a package comment"
    - linters:
        - staticcheck
      text: "SA1019: event.WithIdentifier is deprecated:"

# output configuration options
output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# Override the defaults for each linter specified.
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    default-signifies-exhaustive: true
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - unnamedResult
  govet:
    disable:
      - shadow
  gofmt:
    simplify: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: UK
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 0
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

linters:
  disable-all: true
  enable:
    # Checks for unclosed HTTP response body: https://github.com/timakin/bodyclose
    - bodyclose
    # Checks for struct contained context.Context field: https://github.com/sivchari/containedctx
    - containedctx
    # Checks function and package cyclomatic complexity: https://github.com/bkielbasa/cyclop
    - cyclop
    # Checks for assignments with too many blank identifiers (e.g. x, , , _, := f()): https://github.com/alexkohler/dogsled
    - dogsled
    # Checks for two durations multiplied together: https://github.com/charithe/durationcheck
    - durationcheck
    # Checks for unchecked errors: https://github.com/kisielk/errcheck
    - errcheck
    # Checks for pointers to enclosing loop variables: https://github.com/kyoh86/exportloopref
    - exportloopref
    # Checks that sentinel errors are prefixed with the `Err` and error types are suffixed with the `Error`: https://github.com/Antonboom/errname
    - errname
    # Check exhaustiveness of enum switch statements: https://github.com/nishanths/exhaustive
    - exhaustive
    # Checks for forced type assertions: https://github.com/gostaticanalysis/forcetypeassert
    - forcetypeassert
    # Checks for long functions: https://github.com/ultraware/funlen
    - funlen
    # Check the errors handling expressions: https://github.com/Djarvur/go-err113
    - err113
    # Checks the cognitive complexity of functions: https://github.com/uudashr/gocognit
    - gocognit
    # Checks for repeated strings that could be replaced by a constant: https://github.com/jgautheron/goconst
    - goconst
    # Checks for bugs, performance and style issues: https://github.com/go-critic/go-critic
    - gocritic
    # Checks the cyclomatic complexity of functions: https://github.com/fzipp/gocyclo
    - gocyclo
    # Checks if comments end in a period: https://github.com/tetafro/godot
    - godot
    # Checks whether code was gofumpt-ed: https://github.com/mvdan/gofumpt
    - gofumpt
    - goimports
    # Checks for security problems: https://github.com/securego/gosec
    - gosec
    # Checks if code could be simplified: https://github.com/dominikh/go-tools/tree/master/simple
    - gosimple
    # Checks for suspicious constructs, such as Printf calls whose arguments do not align with the format string: https://golang.org/cmd/vet/
    - govet
    # Checks for assignments to existing variables are unused: https://github.com/gordonklaus/ineffassign
    - ineffassign
    # Checks for slice declarations with non-zero initial length: https://github.com/ashanbrown/makezero
    - makezero
    - misspell
    - nakedret
    # Checks for code that returns nil even if it checks that the error is not nil: https://github.com/gostaticanalysis/nilerr
    - nilerr
    # Checks for deeply nested if statements: https://github.com/nakabonne/nestif
    - nestif
    # Checks for sending http request without context.Context: https://github.com/sonatard/noctx
    - noctx
    # Checks for slice declarations that could potentially be pre-allocated: https://github.com/alexkohler/prealloc
    - prealloc
    # Checks for code that shadows one of Go's predeclared identifiers: https://github.com/nishanths/predeclared
    - predeclared
    # Fast, configurable, extensible, flexible, and beautiful linter for Go: https://github.com/mgechev/revive
    - revive
    # Checks for whether Err of rows is checked successfully: https://github.com/jingyugao/rowserrcheck
    # WARN [linters context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
    - rowserrcheck
    # https://staticcheck.io/
    - staticcheck
    # a replacement for golint: https://github.com/dominikh/go-tools/tree/master/stylecheck
    - stylecheck
    # Checks that sql.Rows and sql.Stmt are closed: https://github.com/ryanrolds/sqlclosecheck
    # WARN [linters context] sqlclosecheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
    - sqlclosecheck
    # linter that makes you use a separate _test package: https://github.com/maratori/testpackage
    - testpackage
    - typecheck
    # Checks for unnecessary type conversions: https://github.com/mdempsky/unconvert
    - unconvert
    # Checks for unused function parameters: https://github.com/mvdan/unparam
    - unparam
    # Checks for unused constants, variables, functions and types: https://github.com/dominikh/go-tools/tree/master/unused
    - unused
    # Checks for wasted assignment statements: https://github.com/sanposhiho/wastedassign
    # WARN [linters context] wastedassign is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
    - wastedassign
    # Checks for detection of leading and trailing whitespace: https://github.com/ultraware/whitespace
    - whitespace
